# Postgres DB
# POSTGRES_CONTAINER=postgres-container
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB_SOURCE=mydatabase
POSTGRES_DB_TARGET=targetdb
POSTGRES_PORT=5432

# Airflow Core
AIRFLOW__CORE__FERNET_KEY=XMiUU0qwWepOAcssh2OpHheSV58dS6jBd2d-zTkTCtA=
AIRFLOW__CORE__EXECUTOR=LocalExecutor
AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
AIRFLOW__CORE__LOAD_EXAMPLES=False
AIRFLOW_UID=50000
AIRFLOW_GID=0

# Airflow Backend DB
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False

# Airflow Init
_AIRFLOW_DB_UPGRADE=True # deprecated
# _AIRFLOW_DB_MIGRATE='true'
_AIRFLOW_WWW_USER_CREATE=True
_AIRFLOW_WWW_USER_USERNAME=airflow
_AIRFLOW_WWW_USER_PASSWORD=airflow

# Airflow Pre-defined Connections
AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT=google-cloud-platform://